yml update

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -7,48 +7,101 @@ on:
     branches: ['*']
 
 jobs:
-  tests:
-    strategy:
-      matrix:
-        python: [3.9]
+  test_python_38:
     runs-on: ubuntu-latest
     env:
       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
       PYTHONPATH: .
     steps:
       - uses: actions/checkout@v2
-      - name: Initialize and update hairy-trumpet submodule
-        run: git submodule update --init --recursive hairy-trumpet
-      - name: Set up Python ${{matrix.python}}
+      - name: Set up Python 3.8
         uses: actions/setup-python@v2
         with:
-          python-version: ${{matrix.python}}
-      - name: Install poppler
-        run: sudo apt-get install -y poppler-utils
-      - name: install metahtml
-        run: |
-          cd metahtml
-          git init
-          git remote add origin https://github.com/mikeizbicki/metahtml
-          git config core.sparseCheckout true
-          echo '/*' > .git/info/sparse-checkout
-          echo '!/tests' >> .git/info/sparse-checkout
-          git pull origin master
-          pip install .
-          cd ..
-      - name: install dependencies
+          python-version: 3.8
+
+      - name: Update submodules
+        run: git submodule update --init --recursive
+
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-      # - name: run query tests
-      #   run: |
-      #     python3 ragnews/__init__.py --query "Who is the current democratic presidential nominee?"
-      #     python3 ragnews/__init__.py --query "What is the policy position of Trump related to illegal Mexican immigrants?"
-      - name: run evaluation test
+
+      - name: Clone and install metahtml
+        run: |
+          git clone --filter=blob:none --no-checkout https://github.com/mikeizbicki/metahtml
+          cd metahtml
+          git sparse-checkout init
+          git sparse-checkout set --cone
+          echo '/*' > .git/info/sparse-checkout
+          echo '!/tests/.cache/' >> .git/info/sparse-checkout
+          git sparse-checkout reapply
+          git checkout master
+          pip install .
+
+      - name: Install expect
+        run: sudo apt-get update && sudo apt-get install -y expect
+
+      - name: Run all files
+        run: |
+          echo 'spawn python3 ragnews.py; expect "ragnews> "; send "Sample input\r"; interact' | expect
+
+      - name: Run evaluation test
         run: |
           python3 ragnews/evaluate.py --data "hairy-trumpet/data/wiki__page=2024_United_States_elections,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]" | tee output.log
           success_ratio=$(grep 'Success ratio:' output.log | awk '{print $3}')
-          echo "Success ratio: $success_ratio"  # Add this line to log the success ratio
+          echo "Success ratio: $success_ratio"
+          if [[ -z "$success_ratio" ]]; then
+            echo "Error: Success ratio is empty or invalid"
+            exit 1
+          fi
+          python -c "assert($success_ratio > 0.7), 'Test failed: Success ratio is less than 0.7'"
+          echo "Test passed with success ratio $success_ratio"
+
+  test_python_39:
+    runs-on: ubuntu-latest
+    env:
+      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
+      PYTHONPATH: .
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+
+      - name: Update submodules
+        run: git submodule update --init --recursive
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+      - name: Clone and install metahtml
+        run: |
+          git clone --filter=blob:none --no-checkout https://github.com/mikeizbicki/metahtml
+          cd metahtml
+          git sparse-checkout init
+          git sparse-checkout set --cone
+          echo '/*' > .git/info/sparse-checkout
+          echo '!/tests/.cache/' >> .git/info/sparse-checkout
+          git sparse-checkout reapply
+          git checkout master
+          pip install .
+
+      - name: Install expect
+        run: sudo apt-get update && sudo apt-get install -y expect
+
+      - name: Run all files
+        run: |
+          echo 'spawn python3 ragnews.py; expect "ragnews> "; send "Sample input\r"; interact' | expect
+
+      - name: Run evaluation test
+        run: |
+          python3 ragnews/evaluate.py --data "hairy-trumpet/data/wiki__page=2024_United_States_elections,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]" | tee output.log
+          success_ratio=$(grep 'Success ratio:' output.log | awk '{print $3}')
+          echo "Success ratio: $success_ratio"
           if [[ -z "$success_ratio" ]]; then
             echo "Error: Success ratio is empty or invalid"
             exit 1
