updated tests removed

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,47 +1,47 @@
-name: tests
+# name: tests
 
-on:
-  push:
-    branches: ['*']
-  pull_request:
-    branches: ['*']
+# on:
+#   push:
+#     branches: ['*']
+#   pull_request:
+#     branches: ['*']
 
-jobs:
-  tests:
-    strategy:
-      matrix:
-        python: [3.9]
-    runs-on: ubuntu-latest
-    env:
-      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          submodules: true
-          fetch-depth: 0 
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          sudo apt-get update && sudo apt-get install -y expect # Install expect
-      - name: Run evaluation script
-        run: |
-          export PYTHONPATH=.
-          accuracy=$(python3 ragnews/evaluate.py --data hairy-trumpet/data/'wiki__page=2024_United_States_presidential_election,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]')
-          echo "Accuracy: $accuracy"
-          echo "::set-output name=accuracy::$accuracy"
-      - name: Verify accuracy
-        run: |
-          accuracy=${{ steps.run_evaluation.outputs.accuracy }}
-          echo "Extracted accuracy: $accuracy"
-          if (( $(echo "$accuracy < 0.7" | bc -l) )); then
-            echo "Accuracy is less than 0.7. Test failed."
-            exit 1
-          else
-            echo "Accuracy is greater than or equal to 0.7. Test passed."
-          fi
+# jobs:
+#   tests:
+#     strategy:
+#       matrix:
+#         python: [3.9]
+#     runs-on: ubuntu-latest
+#     env:
+#       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v3
+#         with:
+#           submodules: true
+#           fetch-depth: 0 
+#       - name: Set up Python ${{ matrix.python }}
+#         uses: actions/setup-python@v2
+#         with:
+#           python-version: ${{ matrix.python }}
+#       - name: Install dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install -r requirements.txt
+#           sudo apt-get update && sudo apt-get install -y expect # Install expect
+#       - name: Run evaluation script
+#         run: |
+#           export PYTHONPATH=.
+#           accuracy=$(python3 ragnews/evaluate.py --data hairy-trumpet/data/'wiki__page=2024_United_States_presidential_election,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]')
+#           echo "Accuracy: $accuracy"
+#           echo "::set-output name=accuracy::$accuracy"
+#       - name: Verify accuracy
+#         run: |
+#           accuracy=${{ steps.run_evaluation.outputs.accuracy }}
+#           echo "Extracted accuracy: $accuracy"
+#           if (( $(echo "$accuracy < 0.7" | bc -l) )); then
+#             echo "Accuracy is less than 0.7. Test failed."
+#             exit 1
+#           else
+#             echo "Accuracy is greater than or equal to 0.7. Test passed."
+#           fi
